// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slizsctvvubqnqgsucsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsaXpzY3R2dnVicW5xZ3N1Y3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNDIwMTgsImV4cCI6MjA2NjkxODAxOH0.WMvMBmEndaTnaKoSNuxpJIYVP6yjmtAE7Zx2YVyzrIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});